{% set name = "pybboxes" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybboxes-{{ version }}.tar.gz
  sha256: 466554e9bf99b53945f82c8118df53aa3ca9071948c47a71dc3a8cc295996af2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - pybboxes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/devrimcavusoglu/pybboxes
  summary: Light Weight Toolkit for Bounding Boxes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - devrimcavusoglu
    - fcakyon
